# Generated by Django 5.1.5 on 2025-01-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_blogpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
    ]
